# ==========================================
# üìß SMTP Email Credentials (Dummy Values)
# ==========================================
SMTP_EMAIL = "your_email_here"
SMTP_APP_PASSWORD = "your_app_password_here"

# ==========================================
# ü§ñ Telegram Bot Credentials (Dummy Values)
# ==========================================
TELEGRAM_BOT_TOKEN = "your_telegram_bot_token_here"
TELEGRAM_CHAT_ID = "your_telegram_chat_id_here"

# ==========================================
# üîç Model Paths (Optional - you can change)
# ==========================================
CROWD_MODEL_PATH = "People_count_model/best.pt"
WEAPON_MODEL_PATH = "weapon_detection_model/best1.pt"
